export const data = {
  world: {
    areas: [],
    characters: [],
    items: [],
    locations: [
      {
        slug: 'spawnlake',
        uid: 'vTm5shJb',
        x: -400,
        y: -597,
        exits: ['AdGMquH_'],
      },
      {
        slug: 'spawnlake_shore',
        uid: 'AdGMquH_',
        x: -395,
        y: -553,
        exits: ['9gx1gQdw'],
      },
      {
        slug: 'forest_path',
        uid: '9gx1gQdw',
        x: -217,
        y: -499,
        exits: ['AdGMquH_', 'vpq2wkZM', 'I&iu5GU1'],
      },
      {
        slug: 'north_exit',
        uid: 'vpq2wkZM',
        x: -92,
        y: -393,
        exits: ['9gx1gQdw', 'r9JTpNBe'],
      },
      {
        slug: 'north_residential',
        uid: 'r9JTpNBe',
        x: 22,
        y: -204,
        exits: ['vpq2wkZM', '88MjFB6v', '87kjcOlj'],
      },
      {
        slug: 'inn_street',
        uid: '88MjFB6v',
        x: -6,
        y: -71,
        exits: ['r9JTpNBe', '2IwPnWo4', 'XOdVqZ2R'],
      },
      {
        slug: 'inn',
        uid: '2IwPnWo4',
        x: -44,
        y: -107,
        exits: ['88MjFB6v', 'HVTgFo7x', 'SbQpKjcC'],
      },
      {
        slug: 'plaza',
        uid: 'XOdVqZ2R',
        x: 0,
        y: 17,
        exits: ['88MjFB6v', 'fIpqTS9u', 'I6c&hdXb', '77UGodwK'],
      },
      {
        slug: 'clinic',
        uid: 'fIpqTS9u',
        x: 43,
        y: 55,
        exits: ['GkLzsCod', 'XOdVqZ2R'],
      },
      {
        slug: 'blacksmith_street',
        uid: 'I6c&hdXb',
        x: -137,
        y: 14,
        exits: ['XOdVqZ2R', '77UGodwK'],
      },
      {
        slug: 'market_west',
        uid: '77UGodwK',
        x: -72,
        y: 103,
        exits: ['XOdVqZ2R', 'I6c&hdXb', 'GkLzsCod'],
      },
      {
        slug: 'market_east',
        uid: 'GkLzsCod',
        x: 51,
        y: 124,
        exits: ['77UGodwK', 'fIpqTS9u', 'ebvZuS52'],
      },
      {
        slug: 'bookstore_street',
        uid: 'ebvZuS52',
        x: 139,
        y: 156,
        exits: ['GkLzsCod', 'CT7QCqPJ', '3U&W5itp'],
      },
      {
        slug: 'residential_south',
        uid: 'CT7QCqPJ',
        x: 241,
        y: 269,
        exits: ['ebvZuS52', 'AE16o1Td', 'iDCuO2eE'],
      },
      {
        slug: 'exit_south',
        uid: 'AE16o1Td',
        x: 372,
        y: 351,
        exits: ['CT7QCqPJ', '4O8zhFYE'],
      },
      {
        slug: 'intersection',
        uid: '4O8zhFYE',
        x: 406,
        y: 540,
        exits: ['TCgPBgqZ', 'Rp0JkVv4', 'AE16o1Td'],
      },
      {
        slug: 'dungeon_one',
        uid: 'TCgPBgqZ',
        x: 508,
        y: 629,
        exits: ['4O8zhFYE'],
      },
      {
        slug: 'dungeon_two',
        uid: 'Rp0JkVv4',
        x: 262,
        y: 594,
        exits: ['4O8zhFYE'],
      },
      {
        slug: 'combat_trainer',
        uid: '87kjcOlj',
        x: 61,
        y: -221,
        exits: ['r9JTpNBe'],
      },
      {
        slug: 'bookstore',
        uid: '3U&W5itp',
        x: 166,
        y: 103,
        exits: ['ebvZuS52'],
      },
      {
        slug: 'maho',
        uid: 'iDCuO2eE',
        x: 259,
        y: 223,
        exits: ['CT7QCqPJ'],
      },
      {
        slug: 'bear_lair',
        uid: 'I&iu5GU1',
        x: -91,
        y: -561,
        exits: ['9gx1gQdw'],
      },
      {
        slug: 'myroom',
        uid: 'HVTgFo7x',
        x: -65,
        y: -70,
        exits: ['2IwPnWo4'],
      },
      {
        uid: 'SbQpKjcC',
        slug: 'inn_basement',
        x: -20,
        y: -157,
        exits: ['2IwPnWo4'],
      },
    ],
    subnodes: [
      {
        slug: 'blacksmith_armor',
        uid: 'DPLJ_G60',
        parent: 'I6c&hdXb',
        x: -164,
        y: -22,
      },
      {
        slug: 'blacksmith_weapons',
        uid: 'RT4Jdr49',
        parent: 'I6c&hdXb',
        x: -137,
        y: -30,
      },
      {
        uid: 'QyG9weFC',
        slug: 'desk',
        x: -85,
        y: -113,
        parent: 'HVTgFo7x',
      },
      {
        uid: 'kyzsaF1E',
        slug: 'bed',
        x: -104,
        y: -70,
        parent: 'HVTgFo7x',
      },
      {
        uid: 'I1PKrb_3',
        slug: 'drawer',
        x: -99.72320000000002,
        y: -105.86719999999998,
        parent: 'QyG9weFC',
      },
      {
        slug: 'asorted_goods',
        uid: 'SdZSP4AG',
        parent: '77UGodwK',
        x: -116,
        y: 65,
      },
      {
        slug: 'food_a',
        uid: 'VRqbyWzJ',
        parent: '77UGodwK',
        x: -36,
        y: 87,
      },
      {
        slug: 'leatherworks',
        uid: 'cg_fgFgU',
        parent: '77UGodwK',
        x: -100,
        y: 129,
      },
      {
        slug: 'jewlery',
        uid: 'nZcr9sEV',
        parent: 'GkLzsCod',
        x: 21,
        y: 146,
      },
      {
        slug: 'herbs_and_potions',
        uid: 'S&6ZPPk5',
        parent: 'GkLzsCod',
        x: 19,
        y: 84,
      },
      {
        slug: 'food_b',
        uid: 'df2HglHF',
        parent: 'GkLzsCod',
        x: 71,
        y: 163,
      },
      {
        slug: 'the_bar',
        uid: 'EE6EVAiy',
        parent: '2IwPnWo4',
        x: -90,
        y: -152,
      },
      {
        slug: 'magic',
        uid: 'gAmwYwOF',
        parent: '3U&W5itp',
        x: 151,
        y: 67,
      },
      {
        slug: 'lore',
        uid: 'I22iIzzK',
        parent: '3U&W5itp',
        x: 185.36160000000007,
        y: 66.96608,
      },
    ],
  },
  journal: {
    aliases: [],
    snippets: [
      {
        key: 'village',
        text: 'Rŏk',
      },
    ],
    defaults: [],
    actions: {
      goto: [],
    },
    sequences: {
      triggers: [],
      nodes: [],
    },
    threads: [],
  },
  ini: {
    spawn_node: 'vTm5shJb',
  },
  kod: {},
};
