/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XEzf4ZbsZCZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"

export function ChatView() {
  return (
    <div className="flex flex-col h-screen">
      <div className="flex-1 overflow-auto p-4">
        <div className="grid gap-4">
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AC</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg p-3 max-w-[75%]">
              <p className="text-sm">
                Hello! How can I assist you today? I'm an AI assistant created by Anthropic to help with a variety of
                tasks.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[75%] text-primary-foreground">
              <p className="text-sm">
                Hi there! I'm wondering if you can help me understand how airplane turbulence works. I'm a bit nervous
                about my first flight coming up.
              </p>
            </div>
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>YO</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AC</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg p-3 max-w-[75%]">
              <p className="text-sm">
                Absolutely, I'd be happy to explain airplane turbulence in a way that's easy to understand. Turbulence
                happens when the plane encounters pockets of air that are moving differently than the surrounding air.
                It's kind of like sailing a boat on choppy water - the boat will bounce and shake a bit, but it's
                completely normal and not dangerous at all.
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[75%] text-primary-foreground">
              <p className="text-sm">
                That makes a lot of sense, thank you! I feel much better about my upcoming flight now. Is there anything
                else I should know before I go?
              </p>
            </div>
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>YO</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AC</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg p-3 max-w-[75%]">
              <p className="text-sm">Here are a few other tips that can help make your first flight a smooth one:</p>
              <ul className="list-disc list-inside mt-2">
                <li>Drink plenty of water to stay hydrated</li>
                <li>Bring noise-cancelling headphones or earplugs</li>
                <li>If you feel anxious, try some deep breathing or meditation exercises</li>
                <li>Don't be afraid to ask the flight attendants for anything you need</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div className="border-t p-4">
        <Textarea
          placeholder="Type your message..."
          className="w-full rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-primary"
          rows={2}
        />
      </div>
    </div>
  )
}
